// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageFingerprint.proto

#ifndef PROTOBUF_ImageFingerprint_2eproto__INCLUDED
#define PROTOBUF_ImageFingerprint_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ImageFingerprint_2eproto();
void protobuf_InitDefaults_ImageFingerprint_2eproto();
void protobuf_AssignDesc_ImageFingerprint_2eproto();
void protobuf_ShutdownFile_ImageFingerprint_2eproto();

class ImageFingerprint;

// ===================================================================

class ImageFingerprint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ImageFingerprint) */ {
 public:
  ImageFingerprint();
  virtual ~ImageFingerprint();

  ImageFingerprint(const ImageFingerprint& from);

  inline ImageFingerprint& operator=(const ImageFingerprint& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImageFingerprint& default_instance();

  static const ImageFingerprint* internal_default_instance();

  void Swap(ImageFingerprint* other);

  // implements Message ----------------------------------------------

  inline ImageFingerprint* New() const { return New(NULL); }

  ImageFingerprint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImageFingerprint& from);
  void MergeFrom(const ImageFingerprint& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ImageFingerprint* other);
  void UnsafeMergeFrom(const ImageFingerprint& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes terms = 1;
  int terms_size() const;
  void clear_terms();
  static const int kTermsFieldNumber = 1;
  const ::std::string& terms(int index) const;
  ::std::string* mutable_terms(int index);
  void set_terms(int index, const ::std::string& value);
  void set_terms(int index, const char* value);
  void set_terms(int index, const void* value, size_t size);
  ::std::string* add_terms();
  void add_terms(const ::std::string& value);
  void add_terms(const char* value);
  void add_terms(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& terms() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_terms();

  // @@protoc_insertion_point(class_scope:ImageFingerprint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> terms_;
  friend void  protobuf_InitDefaults_ImageFingerprint_2eproto_impl();
  friend void  protobuf_AddDesc_ImageFingerprint_2eproto_impl();
  friend void protobuf_AssignDesc_ImageFingerprint_2eproto();
  friend void protobuf_ShutdownFile_ImageFingerprint_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ImageFingerprint> ImageFingerprint_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ImageFingerprint

// repeated bytes terms = 1;
inline int ImageFingerprint::terms_size() const {
  return terms_.size();
}
inline void ImageFingerprint::clear_terms() {
  terms_.Clear();
}
inline const ::std::string& ImageFingerprint::terms(int index) const {
  // @@protoc_insertion_point(field_get:ImageFingerprint.terms)
  return terms_.Get(index);
}
inline ::std::string* ImageFingerprint::mutable_terms(int index) {
  // @@protoc_insertion_point(field_mutable:ImageFingerprint.terms)
  return terms_.Mutable(index);
}
inline void ImageFingerprint::set_terms(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ImageFingerprint.terms)
  terms_.Mutable(index)->assign(value);
}
inline void ImageFingerprint::set_terms(int index, const char* value) {
  terms_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ImageFingerprint.terms)
}
inline void ImageFingerprint::set_terms(int index, const void* value, size_t size) {
  terms_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ImageFingerprint.terms)
}
inline ::std::string* ImageFingerprint::add_terms() {
  // @@protoc_insertion_point(field_add_mutable:ImageFingerprint.terms)
  return terms_.Add();
}
inline void ImageFingerprint::add_terms(const ::std::string& value) {
  terms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ImageFingerprint.terms)
}
inline void ImageFingerprint::add_terms(const char* value) {
  terms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ImageFingerprint.terms)
}
inline void ImageFingerprint::add_terms(const void* value, size_t size) {
  terms_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ImageFingerprint.terms)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ImageFingerprint::terms() const {
  // @@protoc_insertion_point(field_list:ImageFingerprint.terms)
  return terms_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ImageFingerprint::mutable_terms() {
  // @@protoc_insertion_point(field_mutable_list:ImageFingerprint.terms)
  return &terms_;
}

inline const ImageFingerprint* ImageFingerprint::internal_default_instance() {
  return &ImageFingerprint_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ImageFingerprint_2eproto__INCLUDED
