// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueueMetadata.proto

#ifndef PROTOBUF_QueueMetadata_2eproto__INCLUDED
#define PROTOBUF_QueueMetadata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_QueueMetadata_2eproto();
void protobuf_InitDefaults_QueueMetadata_2eproto();
void protobuf_AssignDesc_QueueMetadata_2eproto();
void protobuf_ShutdownFile_QueueMetadata_2eproto();

class QueueMetadata;

// ===================================================================

class QueueMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:QueueMetadata) */ {
 public:
  QueueMetadata();
  virtual ~QueueMetadata();

  QueueMetadata(const QueueMetadata& from);

  inline QueueMetadata& operator=(const QueueMetadata& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueueMetadata& default_instance();

  static const QueueMetadata* internal_default_instance();

  void Swap(QueueMetadata* other);

  // implements Message ----------------------------------------------

  inline QueueMetadata* New() const { return New(NULL); }

  QueueMetadata* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QueueMetadata& from);
  void MergeFrom(const QueueMetadata& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(QueueMetadata* other);
  void UnsafeMergeFrom(const QueueMetadata& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 priority = 1;
  bool has_priority() const;
  void clear_priority();
  static const int kPriorityFieldNumber = 1;
  ::google::protobuf::int32 priority() const;
  void set_priority(::google::protobuf::int32 value);

  // optional int64 sequence = 2;
  bool has_sequence() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  ::google::protobuf::int64 sequence() const;
  void set_sequence(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:QueueMetadata)
 private:
  inline void set_has_priority();
  inline void clear_has_priority();
  inline void set_has_sequence();
  inline void clear_has_sequence();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 sequence_;
  ::google::protobuf::int32 priority_;
  friend void  protobuf_InitDefaults_QueueMetadata_2eproto_impl();
  friend void  protobuf_AddDesc_QueueMetadata_2eproto_impl();
  friend void protobuf_AssignDesc_QueueMetadata_2eproto();
  friend void protobuf_ShutdownFile_QueueMetadata_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<QueueMetadata> QueueMetadata_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// QueueMetadata

// optional int32 priority = 1;
inline bool QueueMetadata::has_priority() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QueueMetadata::set_has_priority() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QueueMetadata::clear_has_priority() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QueueMetadata::clear_priority() {
  priority_ = 0;
  clear_has_priority();
}
inline ::google::protobuf::int32 QueueMetadata::priority() const {
  // @@protoc_insertion_point(field_get:QueueMetadata.priority)
  return priority_;
}
inline void QueueMetadata::set_priority(::google::protobuf::int32 value) {
  set_has_priority();
  priority_ = value;
  // @@protoc_insertion_point(field_set:QueueMetadata.priority)
}

// optional int64 sequence = 2;
inline bool QueueMetadata::has_sequence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QueueMetadata::set_has_sequence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QueueMetadata::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QueueMetadata::clear_sequence() {
  sequence_ = GOOGLE_LONGLONG(0);
  clear_has_sequence();
}
inline ::google::protobuf::int64 QueueMetadata::sequence() const {
  // @@protoc_insertion_point(field_get:QueueMetadata.sequence)
  return sequence_;
}
inline void QueueMetadata::set_sequence(::google::protobuf::int64 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:QueueMetadata.sequence)
}

inline const QueueMetadata* QueueMetadata::internal_default_instance() {
  return &QueueMetadata_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_QueueMetadata_2eproto__INCLUDED
