# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_shared_icuuc_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(abspath $(LOCAL_PATH)/third_party/shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES :=

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
GYP_TARGET_DEPENDENCIES += $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/shared/icu/source/common/appendable.cpp \
	third_party/shared/icu/source/common/bmpset.cpp \
	third_party/shared/icu/source/common/brkeng.cpp \
	third_party/shared/icu/source/common/brkiter.cpp \
	third_party/shared/icu/source/common/bytestream.cpp \
	third_party/shared/icu/source/common/bytestrie.cpp \
	third_party/shared/icu/source/common/bytestriebuilder.cpp \
	third_party/shared/icu/source/common/bytestrieiterator.cpp \
	third_party/shared/icu/source/common/caniter.cpp \
	third_party/shared/icu/source/common/chariter.cpp \
	third_party/shared/icu/source/common/charstr.cpp \
	third_party/shared/icu/source/common/cmemory.c \
	third_party/shared/icu/source/common/cstring.c \
	third_party/shared/icu/source/common/cwchar.c \
	third_party/shared/icu/source/common/dictbe.cpp \
	third_party/shared/icu/source/common/dictionarydata.cpp \
	third_party/shared/icu/source/common/dtintrv.cpp \
	third_party/shared/icu/source/common/errorcode.cpp \
	third_party/shared/icu/source/common/filterednormalizer2.cpp \
	third_party/shared/icu/source/common/icudataver.c \
	third_party/shared/icu/source/common/icuplug.c \
	third_party/shared/icu/source/common/listformatter.cpp \
	third_party/shared/icu/source/common/locavailable.cpp \
	third_party/shared/icu/source/common/locbased.cpp \
	third_party/shared/icu/source/common/locdispnames.cpp \
	third_party/shared/icu/source/common/locid.cpp \
	third_party/shared/icu/source/common/loclikely.cpp \
	third_party/shared/icu/source/common/locmap.c \
	third_party/shared/icu/source/common/locresdata.cpp \
	third_party/shared/icu/source/common/locutil.cpp \
	third_party/shared/icu/source/common/messagepattern.cpp \
	third_party/shared/icu/source/common/mutex.cpp \
	third_party/shared/icu/source/common/normalizer2.cpp \
	third_party/shared/icu/source/common/normalizer2impl.cpp \
	third_party/shared/icu/source/common/normlzr.cpp \
	third_party/shared/icu/source/common/parsepos.cpp \
	third_party/shared/icu/source/common/patternprops.cpp \
	third_party/shared/icu/source/common/propname.cpp \
	third_party/shared/icu/source/common/propsvec.c \
	third_party/shared/icu/source/common/punycode.cpp \
	third_party/shared/icu/source/common/putil.cpp \
	third_party/shared/icu/source/common/rbbi.cpp \
	third_party/shared/icu/source/common/rbbidata.cpp \
	third_party/shared/icu/source/common/rbbinode.cpp \
	third_party/shared/icu/source/common/rbbirb.cpp \
	third_party/shared/icu/source/common/rbbiscan.cpp \
	third_party/shared/icu/source/common/rbbisetb.cpp \
	third_party/shared/icu/source/common/rbbistbl.cpp \
	third_party/shared/icu/source/common/rbbitblb.cpp \
	third_party/shared/icu/source/common/resbund.cpp \
	third_party/shared/icu/source/common/resbund_cnv.cpp \
	third_party/shared/icu/source/common/ruleiter.cpp \
	third_party/shared/icu/source/common/schriter.cpp \
	third_party/shared/icu/source/common/serv.cpp \
	third_party/shared/icu/source/common/servlk.cpp \
	third_party/shared/icu/source/common/servlkf.cpp \
	third_party/shared/icu/source/common/servls.cpp \
	third_party/shared/icu/source/common/servnotf.cpp \
	third_party/shared/icu/source/common/servrbf.cpp \
	third_party/shared/icu/source/common/servslkf.cpp \
	third_party/shared/icu/source/common/stringpiece.cpp \
	third_party/shared/icu/source/common/stringtriebuilder.cpp \
	third_party/shared/icu/source/common/uarrsort.c \
	third_party/shared/icu/source/common/ubidi.c \
	third_party/shared/icu/source/common/ubidi_props.c \
	third_party/shared/icu/source/common/ubidiln.c \
	third_party/shared/icu/source/common/ubidiwrt.c \
	third_party/shared/icu/source/common/ubrk.cpp \
	third_party/shared/icu/source/common/ucase.cpp \
	third_party/shared/icu/source/common/ucasemap.cpp \
	third_party/shared/icu/source/common/ucasemap_titlecase_brkiter.cpp \
	third_party/shared/icu/source/common/ucat.c \
	third_party/shared/icu/source/common/uchar.c \
	third_party/shared/icu/source/common/ucharstrie.cpp \
	third_party/shared/icu/source/common/ucharstriebuilder.cpp \
	third_party/shared/icu/source/common/ucharstrieiterator.cpp \
	third_party/shared/icu/source/common/uchriter.cpp \
	third_party/shared/icu/source/common/ucln_cmn.c \
	third_party/shared/icu/source/common/ucmndata.c \
	third_party/shared/icu/source/common/ucnv.c \
	third_party/shared/icu/source/common/ucnv2022.cpp \
	third_party/shared/icu/source/common/ucnv_bld.cpp \
	third_party/shared/icu/source/common/ucnv_cb.c \
	third_party/shared/icu/source/common/ucnv_cnv.c \
	third_party/shared/icu/source/common/ucnv_ct.c \
	third_party/shared/icu/source/common/ucnv_err.c \
	third_party/shared/icu/source/common/ucnv_ext.cpp \
	third_party/shared/icu/source/common/ucnv_io.cpp \
	third_party/shared/icu/source/common/ucnv_lmb.c \
	third_party/shared/icu/source/common/ucnv_set.c \
	third_party/shared/icu/source/common/ucnv_u16.c \
	third_party/shared/icu/source/common/ucnv_u32.c \
	third_party/shared/icu/source/common/ucnv_u7.c \
	third_party/shared/icu/source/common/ucnv_u8.c \
	third_party/shared/icu/source/common/ucnvbocu.cpp \
	third_party/shared/icu/source/common/ucnvdisp.c \
	third_party/shared/icu/source/common/ucnvhz.c \
	third_party/shared/icu/source/common/ucnvisci.c \
	third_party/shared/icu/source/common/ucnvlat1.c \
	third_party/shared/icu/source/common/ucnvmbcs.c \
	third_party/shared/icu/source/common/ucnvscsu.c \
	third_party/shared/icu/source/common/ucnvsel.cpp \
	third_party/shared/icu/source/common/ucol_swp.cpp \
	third_party/shared/icu/source/common/udata.cpp \
	third_party/shared/icu/source/common/udatamem.c \
	third_party/shared/icu/source/common/udataswp.c \
	third_party/shared/icu/source/common/uenum.c \
	third_party/shared/icu/source/common/uhash.c \
	third_party/shared/icu/source/common/uhash_us.cpp \
	third_party/shared/icu/source/common/uidna.cpp \
	third_party/shared/icu/source/common/uinit.c \
	third_party/shared/icu/source/common/uinvchar.c \
	third_party/shared/icu/source/common/uiter.cpp \
	third_party/shared/icu/source/common/ulist.c \
	third_party/shared/icu/source/common/uloc.cpp \
	third_party/shared/icu/source/common/uloc_tag.c \
	third_party/shared/icu/source/common/umapfile.c \
	third_party/shared/icu/source/common/umath.c \
	third_party/shared/icu/source/common/umutex.cpp \
	third_party/shared/icu/source/common/unames.cpp \
	third_party/shared/icu/source/common/unifilt.cpp \
	third_party/shared/icu/source/common/unifunct.cpp \
	third_party/shared/icu/source/common/uniset.cpp \
	third_party/shared/icu/source/common/uniset_closure.cpp \
	third_party/shared/icu/source/common/uniset_props.cpp \
	third_party/shared/icu/source/common/unisetspan.cpp \
	third_party/shared/icu/source/common/unistr.cpp \
	third_party/shared/icu/source/common/unistr_case.cpp \
	third_party/shared/icu/source/common/unistr_case_locale.cpp \
	third_party/shared/icu/source/common/unistr_cnv.cpp \
	third_party/shared/icu/source/common/unistr_props.cpp \
	third_party/shared/icu/source/common/unistr_titlecase_brkiter.cpp \
	third_party/shared/icu/source/common/unorm.cpp \
	third_party/shared/icu/source/common/unorm_it.c \
	third_party/shared/icu/source/common/unormcmp.cpp \
	third_party/shared/icu/source/common/uobject.cpp \
	third_party/shared/icu/source/common/uprops.cpp \
	third_party/shared/icu/source/common/ures_cnv.c \
	third_party/shared/icu/source/common/uresbund.cpp \
	third_party/shared/icu/source/common/uresdata.c \
	third_party/shared/icu/source/common/usc_impl.c \
	third_party/shared/icu/source/common/uscript.c \
	third_party/shared/icu/source/common/uscript_props.cpp \
	third_party/shared/icu/source/common/uset.cpp \
	third_party/shared/icu/source/common/uset_props.cpp \
	third_party/shared/icu/source/common/usetiter.cpp \
	third_party/shared/icu/source/common/ushape.cpp \
	third_party/shared/icu/source/common/usprep.cpp \
	third_party/shared/icu/source/common/ustack.cpp \
	third_party/shared/icu/source/common/ustr_cnv.c \
	third_party/shared/icu/source/common/ustr_titlecase_brkiter.cpp \
	third_party/shared/icu/source/common/ustr_wcs.cpp \
	third_party/shared/icu/source/common/ustrcase.cpp \
	third_party/shared/icu/source/common/ustrcase_locale.cpp \
	third_party/shared/icu/source/common/ustrenum.cpp \
	third_party/shared/icu/source/common/ustrfmt.c \
	third_party/shared/icu/source/common/ustring.cpp \
	third_party/shared/icu/source/common/ustrtrns.cpp \
	third_party/shared/icu/source/common/utext.cpp \
	third_party/shared/icu/source/common/utf_impl.c \
	third_party/shared/icu/source/common/util.cpp \
	third_party/shared/icu/source/common/util_props.cpp \
	third_party/shared/icu/source/common/utrace.c \
	third_party/shared/icu/source/common/utrie.cpp \
	third_party/shared/icu/source/common/utrie2.cpp \
	third_party/shared/icu/source/common/utrie2_builder.cpp \
	third_party/shared/icu/source/common/uts46.cpp \
	third_party/shared/icu/source/common/utypes.c \
	third_party/shared/icu/source/common/uvector.cpp \
	third_party/shared/icu/source/common/uvectr32.cpp \
	third_party/shared/icu/source/common/uvectr64.cpp \
	third_party/shared/icu/source/common/wintz.c


# Flags passed to both C and C++ files.
MY_CFLAGS_Default := \
	-DU_STATIC_IMPLEMENTATION \
	-DU_USING_ICU_NAMESPACE=0 \
	-DU_CHARSET_IS_UTF8=1 \
	-DU_NO_DEFAULT_INCLUDE_UTF_HEADERS1 \
	-D__ANDROID__ \
	-DU_HAVE_STD_STRING=1 \
	-DU_COMMON_IMPLEMENTATION

MY_DEFS_Default := \
	'-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1' \
	'-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2' \
	'-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4' \
	'-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Default := \
	$(LOCAL_PATH)/third_party/shared/icu/source/common \
	$(LOCAL_PATH)/third_party/shared/icu/source/i18n \
	$(LOCAL_PATH)/third_party/shared/icu/source/tools/tzcode


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Default := \
	-std=c++11 \
	-stdlib=libc++ \
	-frtti \
	-g \
	-Wno-deprecated-declarations \
	-Wno-logical-op-parentheses \
	-Wno-tautological-compare \
	-Wno-header-hygiene \
	-Wno-return-type-c-linkage \
	-frtti \
	-fno-exceptions \
	-I../../../android-ndk/sources/android/support/include


LOCAL_CFLAGS := $(MY_CFLAGS_$(GYP_CONFIGURATION)) $(MY_DEFS_$(GYP_CONFIGURATION))
LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES_$(GYP_CONFIGURATION))
LOCAL_CPPFLAGS := $(LOCAL_CPPFLAGS_$(GYP_CONFIGURATION))
### Rules for final target.

LOCAL_LDFLAGS_Default :=


LOCAL_LDFLAGS := $(LOCAL_LDFLAGS_$(GYP_CONFIGURATION))

LOCAL_STATIC_LIBRARIES :=

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES :=

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_shared_icuuc_gyp

# Alias gyp target name.
.PHONY: icuuc
icuuc: third_party_shared_icuuc_gyp

include $(BUILD_STATIC_LIBRARY)
